### ISSUE TITLE
Refactor to use the new Rust client

### ISSUE THREAD

**Issue by hug-dev** [parallaxsecond/parsec-client-test#20]
A Rust client is going to be created parallaxsecond/parsec#127, this repository should be based on it and only contain the specific methods that are only useful for testing.

**Comment by ionut-arm** [comment]
I'm guessing it's not worth waiting for the Rust client to be done and the test client moved on top of it? Would rid you of the need to do this

**Comment by hug-dev** [comment]
I think here and in parallaxsecond/parsec#127 wherever I wrote "Rust Client" I meant "Rust Core Client" which is the part that is very similar between those two projects.
Once the Rust Core Client is done (and on crates.io) that should be easy to only keep from the Test client the Abstract layer and use the Rust Client for the rest.

**Comment by hug-dev** [comment]
Until the Test client is not a Rust crate, what we probably do not want as it should not be advertised as a real client, we will always have the problem that the interface version needs to be the same in the test client and in the service.
Moreover, now that most of the Test Client has actually been moved to the Rust Client, its content will become very small (only the `abstract_test_client.rs` file if Im not wrong).

Because of those two points: would it make sense (and could it work) to move the Test client back into Parsec, as a module in the `tests` folder?

**Comment by hug-dev** [comment]
This is done in parallaxsecond/parsec#150
